"""SCIP index parser.

This module provides a small, typed API around the SCIP protobuf schema:

- Load `.scip` index files (protobuf `scip.Index`)
- Extract occurrences with definition/reference roles
- Parse symbol identifiers into (scheme, package, descriptors)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

from google.protobuf.message import DecodeError

from app.scip._proto import scip_pb2

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator
    from os import PathLike


# NOTE: `scip_pb2.py` is generated by `protoc` and constructs message classes
# dynamically at import time. Static type checkers don't reliably see
# `scip_pb2.Index`, `scip_pb2.Document`, etc. Use dynamic lookups to avoid
# false-positive "unknown attribute" diagnostics.
_IndexMessage = getattr(scip_pb2, "Index")  # noqa: B009


_ROLE_DEFINITION = 0x1
_ROLE_IMPORT = 0x2
_ROLE_WRITE_ACCESS = 0x4
_ROLE_READ_ACCESS = 0x8
_ROLE_GENERATED = 0x10
_ROLE_TEST = 0x20
_ROLE_FORWARD_DEFINITION = 0x40


@dataclass(frozen=True)
class ScipRange:
    """Half-open [start, end) range with 0-based line/character offsets."""

    start_line: int
    start_character: int
    end_line: int
    end_character: int

    @property
    def start_line_1_based(self) -> int:
        return self.start_line + 1

    @property
    def end_line_1_based(self) -> int:
        return self.end_line + 1


@dataclass(frozen=True)
class ScipDocumentOccurrence:
    relative_path: str
    symbol: str
    roles: frozenset[str]
    range: ScipRange
    enclosing_range: ScipRange | None


@dataclass(frozen=True)
class ScipDocument:
    relative_path: str
    language: str
    occurrences: tuple[ScipDocumentOccurrence, ...]
    symbols: tuple[str, ...]


@dataclass(frozen=True)
class ScipIndex:
    """Parsed index with lightweight, derived views."""

    metadata_project_root: str
    documents: tuple[ScipDocument, ...]
    external_symbols: tuple[str, ...]

    def iter_occurrences(self) -> Iterator[ScipDocumentOccurrence]:
        for doc in self.documents:
            yield from doc.occurrences


@dataclass(frozen=True)
class SymbolDescriptor:
    """One descriptor element inside a SCIP symbol."""

    name: str
    kind: str
    disambiguator: str | None = None


@dataclass(frozen=True)
class SymbolIdentifier:
    """Structured representation of a SCIP symbol string."""

    scheme: str | None
    manager: str | None
    package_name: str | None
    version: str | None
    descriptors: tuple[SymbolDescriptor, ...]
    local_id: str | None

    @property
    def is_local(self) -> bool:
        return self.local_id is not None


class ScipParser:
    """Parser for `.scip` index files."""

    def parse_file(self, path: str | PathLike[str]) -> ScipIndex:
        data = Path(path).read_bytes()
        return self.parse_bytes(data)

    def parse_bytes(self, data: bytes) -> ScipIndex:
        index: Any = _IndexMessage()
        try:
            index.ParseFromString(data)
        except DecodeError as exc:  # pragma: no cover
            raise ValueError("Invalid SCIP index payload") from exc

        return self._build_index(index)

    def _build_index(self, index: Any) -> ScipIndex:
        documents = tuple(self._build_document(doc) for doc in index.documents)
        external_symbols = tuple(sym.symbol for sym in index.external_symbols)
        return ScipIndex(
            metadata_project_root=index.metadata.project_root,
            documents=documents,
            external_symbols=external_symbols,
        )

    def _build_document(self, doc: Any) -> ScipDocument:
        occurrences = tuple(
            self._build_occurrence(doc.relative_path, occ) for occ in doc.occurrences
        )
        symbols = tuple(info.symbol for info in doc.symbols)
        return ScipDocument(
            relative_path=doc.relative_path,
            language=doc.language,
            occurrences=occurrences,
            symbols=symbols,
        )

    def _build_occurrence(self, relative_path: str, occ: Any) -> ScipDocumentOccurrence:
        symbol = occ.symbol
        roles = _decode_roles(occ.symbol_roles)
        return ScipDocumentOccurrence(
            relative_path=relative_path,
            symbol=symbol,
            roles=roles,
            range=_decode_range(occ.range),
            enclosing_range=_decode_range(occ.enclosing_range) if occ.enclosing_range else None,
        )

    def occurrences_by_file(
        self, index: ScipIndex
    ) -> dict[str, tuple[ScipDocumentOccurrence, ...]]:
        return {doc.relative_path: doc.occurrences for doc in index.documents}

    def occurrences_by_symbol(self, index: ScipIndex) -> dict[str, list[ScipDocumentOccurrence]]:
        mapping: dict[str, list[ScipDocumentOccurrence]] = {}
        for occ in index.iter_occurrences():
            if not occ.symbol:
                continue
            mapping.setdefault(occ.symbol, []).append(occ)
        return mapping

    def definition_occurrences(self, index: ScipIndex) -> Iterator[ScipDocumentOccurrence]:
        for occ in index.iter_occurrences():
            if "definition" in occ.roles:
                yield occ

    def reference_occurrences(self, index: ScipIndex) -> Iterator[ScipDocumentOccurrence]:
        for occ in index.iter_occurrences():
            if "reference" in occ.roles:
                yield occ

    def parse_symbols(self, symbols: Iterable[str]) -> Iterator[SymbolIdentifier]:
        for symbol in symbols:
            yield parse_symbol_identifier(symbol)


def _decode_roles(symbol_roles: int) -> frozenset[str]:
    roles: set[str] = set()
    if symbol_roles & _ROLE_DEFINITION:
        roles.add("definition")
    else:
        roles.add("reference")
    if symbol_roles & _ROLE_IMPORT:
        roles.add("import")
    if symbol_roles & _ROLE_WRITE_ACCESS:
        roles.add("write")
    if symbol_roles & _ROLE_READ_ACCESS:
        roles.add("read")
    if symbol_roles & _ROLE_GENERATED:
        roles.add("generated")
    if symbol_roles & _ROLE_TEST:
        roles.add("test")
    if symbol_roles & _ROLE_FORWARD_DEFINITION:
        roles.add("forward_definition")
    return frozenset(roles)


def _decode_range(raw: Iterable[int]) -> ScipRange:
    values = list(raw)
    if len(values) == 3:
        start_line, start_character, end_character = values
        end_line = start_line
    elif len(values) == 4:
        start_line, start_character, end_line, end_character = values
    else:
        raise ValueError(f"Invalid SCIP range encoding length: {len(values)}")
    return ScipRange(
        start_line=start_line,
        start_character=start_character,
        end_line=end_line,
        end_character=end_character,
    )


def parse_symbol_identifier(symbol: str) -> SymbolIdentifier:
    """Parse a SCIP symbol string according to the grammar in `scip.proto`."""

    if symbol.startswith("local "):
        local_id = symbol.removeprefix("local ")
        if not local_id:
            raise ValueError("Invalid local symbol")
        return SymbolIdentifier(
            scheme=None,
            manager=None,
            package_name=None,
            version=None,
            descriptors=(),
            local_id=local_id,
        )

    scheme, i = _parse_space_part(symbol, 0)
    manager, i = _parse_space_part(symbol, i)
    package_name, i = _parse_space_part(symbol, i)
    version, i = _parse_space_part(symbol, i)
    if i >= len(symbol):
        raise ValueError("Invalid SCIP symbol: missing descriptors")
    descriptors = tuple(_parse_descriptors(symbol[i:]))
    if not descriptors:
        raise ValueError("Invalid SCIP symbol: missing descriptors")
    return SymbolIdentifier(
        scheme=scheme,
        manager=manager,
        package_name=package_name,
        version=version,
        descriptors=descriptors,
        local_id=None,
    )


def _parse_space_part(s: str, start: int) -> tuple[str, int]:
    if start >= len(s):
        raise ValueError("Unexpected end of symbol")

    out: list[str] = []
    i = start
    in_backticks = False
    while i < len(s):
        ch = s[i]
        if in_backticks:
            if ch == "`":
                if i + 1 < len(s) and s[i + 1] == "`":
                    out.append("`")
                    i += 2
                    continue
                in_backticks = False
                out.append("`")
                i += 1
                continue
            out.append(ch)
            i += 1
            continue

        if ch == "`":
            in_backticks = True
            out.append(ch)
            i += 1
            continue

        if ch == " ":
            if i + 1 < len(s) and s[i + 1] == " ":
                out.append(" ")
                i += 2
                continue
            break

        out.append(ch)
        i += 1

    part = "".join(out)
    if not part:
        raise ValueError("Invalid SCIP symbol: empty part")
    if i >= len(s) or s[i] != " ":
        raise ValueError("Invalid SCIP symbol: expected space")
    return part, i + 1


def _parse_descriptors(s: str) -> Iterator[SymbolDescriptor]:
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == "[":
            name, i = _parse_between_delimiters(s, i, open_ch="[", close_ch="]")
            yield SymbolDescriptor(name=name, kind="type_parameter")
            continue
        if ch == "(":
            name, i = _parse_between_delimiters(s, i, open_ch="(", close_ch=")")
            yield SymbolDescriptor(name=name, kind="parameter")
            continue

        name, i = _parse_identifier(s, i)
        if i >= len(s):
            raise ValueError("Invalid descriptor: missing suffix")
        suffix = s[i]
        if suffix == "/":
            yield SymbolDescriptor(name=name, kind="namespace")
            i += 1
            continue
        if suffix == "#":
            yield SymbolDescriptor(name=name, kind="type")
            i += 1
            continue
        if suffix == ".":
            yield SymbolDescriptor(name=name, kind="term")
            i += 1
            continue
        if suffix == ":":
            yield SymbolDescriptor(name=name, kind="meta")
            i += 1
            continue
        if suffix == "!":
            yield SymbolDescriptor(name=name, kind="macro")
            i += 1
            continue
        if suffix == "(":
            disambiguator, i = _parse_method_disambiguator(s, i)
            yield SymbolDescriptor(name=name, kind="method", disambiguator=disambiguator)
            continue
        raise ValueError(f"Invalid descriptor suffix: {suffix!r}")


def _parse_identifier(s: str, start: int) -> tuple[str, int]:
    if start >= len(s):
        raise ValueError("Unexpected end of descriptor")

    if s[start] == "`":
        escaped: list[str] = []
        i = start + 1
        while i < len(s):
            ch = s[i]
            if ch == "`":
                if i + 1 < len(s) and s[i + 1] == "`":
                    escaped.append("`")
                    i += 2
                    continue
                return "".join(escaped), i + 1
            escaped.append(ch)
            i += 1
        raise ValueError("Unterminated backtick identifier")

    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+$-")
    i = start
    out: list[str] = []
    while i < len(s) and s[i] in allowed:
        out.append(s[i])
        i += 1
    if not out:
        raise ValueError("Invalid identifier")
    return "".join(out), i


def _parse_between_delimiters(
    s: str, start: int, *, open_ch: str, close_ch: str
) -> tuple[str, int]:
    if start >= len(s) or s[start] != open_ch:
        raise ValueError("Invalid delimited descriptor")
    name, i = _parse_identifier(s, start + 1)
    if i >= len(s) or s[i] != close_ch:
        raise ValueError("Invalid delimited descriptor")
    return name, i + 1


def _parse_method_disambiguator(s: str, start: int) -> tuple[str | None, int]:
    if start >= len(s) or s[start] != "(":
        raise ValueError("Invalid method descriptor")
    i = start + 1
    if i >= len(s):
        raise ValueError("Invalid method descriptor")
    if s[i] == ")":
        i += 1
        if i >= len(s) or s[i] != ".":
            raise ValueError("Invalid method descriptor")
        return None, i + 1

    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+$-")
    out: list[str] = []
    while i < len(s) and s[i] in allowed:
        out.append(s[i])
        i += 1
    if not out:
        raise ValueError("Invalid method disambiguator")
    if i >= len(s) or s[i] != ")":
        raise ValueError("Invalid method descriptor")
    i += 1
    if i >= len(s) or s[i] != ".":
        raise ValueError("Invalid method descriptor")
    return "".join(out), i + 1
